/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package doctor;

import config.Session;
import config.dbConnector;
import frontdesk.*;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;
import login.*;

/**
 *
 * @author w10
 */
public class doctorProfile extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public doctorProfile() {
        initComponents();
        this.setTitle("Medmate");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        time_disp = new javax.swing.JLabel();
        date_disp = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        displayname = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        Doctor = new javax.swing.JLabel();
        fnamedisp = new javax.swing.JLabel();
        lnamedisp = new javax.swing.JLabel();
        contactdisp = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        statusdisp = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Doctor1 = new javax.swing.JLabel();
        fnamedisp6 = new javax.swing.JLabel();
        fnamedisp7 = new javax.swing.JLabel();
        fnamedisp8 = new javax.swing.JLabel();
        fnamedisp9 = new javax.swing.JLabel();
        fullnamedisp = new javax.swing.JLabel();
        passdisp = new javax.swing.JLabel();
        usernamedisp = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(223, 208, 184));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(21, 52, 72));
        jPanel2.setForeground(new java.awt.Color(77, 134, 156));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Untitled_design__4_-removebg-preview.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 180, 10));

        jPanel6.setBackground(new java.awt.Color(21, 52, 72));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(238, 247, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-logout-30.png"))); // NOI18N
        jLabel4.setText(" Logout");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 200, 40));

        jPanel7.setBackground(new java.awt.Color(21, 52, 72));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 247, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-dashboard-30 (1).png"))); // NOI18N
        jLabel5.setText(" Dashboard");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 40));

        jPanel10.setBackground(new java.awt.Color(21, 52, 72));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(238, 247, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-reports-30.png"))); // NOI18N
        jLabel8.setText("Appointments");
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, 40));

        jPanel11.setBackground(new java.awt.Color(21, 52, 72));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(238, 247, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-users-30.png"))); // NOI18N
        jLabel9.setText("Patients");
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 40));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 200, 550);

        jPanel4.setBackground(new java.awt.Color(148, 137, 121));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        time_disp.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        time_disp.setForeground(new java.awt.Color(255, 255, 255));
        time_disp.setText("00:00:00");
        jPanel4.add(time_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, 20));

        date_disp.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        date_disp.setForeground(new java.awt.Color(255, 255, 255));
        date_disp.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        date_disp.setText("00-00-000");
        jPanel4.add(date_disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 100, 20));

        jPanel3.setBackground(new java.awt.Color(223, 208, 184));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(223, 208, 184)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        displayname.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        displayname.setForeground(new java.awt.Color(0, 51, 51));
        displayname.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/icons8-user-25 (1).png"))); // NOI18N
        displayname.setText("Shaira Mae Tolentino");
        jPanel3.add(displayname, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 0, 170, 40));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 11, 190, -1));

        jPanel1.add(jPanel4);
        jPanel4.setBounds(200, 0, 600, 60);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 320, 10));

        Doctor.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Doctor.setText("Doctor");
        jPanel5.add(Doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, 30));

        fnamedisp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fnamedisp.setText("First Name:");
        jPanel5.add(fnamedisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 220, 20));

        lnamedisp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lnamedisp.setText("Last Name:");
        jPanel5.add(lnamedisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, 20));

        contactdisp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        contactdisp.setText("Contact Number: ");
        jPanel5.add(contactdisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 220, 20));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 320, 10));

        statusdisp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        statusdisp.setText("Status:");
        jPanel5.add(statusdisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 20));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Doctor1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Doctor1.setText("Doctor");
        jPanel8.add(Doctor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, 30));

        fnamedisp6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fnamedisp6.setText("First Name:");
        jPanel8.add(fnamedisp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 100, 20));

        fnamedisp7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fnamedisp7.setText("Last Name:");
        jPanel8.add(fnamedisp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 20));

        fnamedisp8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fnamedisp8.setText("Contact Number: ");
        jPanel8.add(fnamedisp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 20));

        fnamedisp9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        fnamedisp9.setText("Status:");
        jPanel8.add(fnamedisp9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 100, 20));

        fullnamedisp.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        fullnamedisp.setText("Shaira Mae Tolentino");
        jPanel8.add(fullnamedisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 330, 40));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        passdisp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        passdisp.setText("Password:");
        jPanel5.add(passdisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 210, 20));

        usernamedisp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        usernamedisp.setText("Username:");
        jPanel5.add(usernamedisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, 20));

        jButton1.setText("Change Password");
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 393, 330, 40));

        jPanel1.add(jPanel5);
        jPanel5.setBounds(410, 80, 370, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        loginDash logout = new loginDash();
        logout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Timer timer = new Timer(0, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
        
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
        String time = timeFormat.format(now);
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("MM-dd-yyyy");
        String date = dateFormat.format(now);
        
        date_disp.setText(date);
        time_disp.setText(time);
                
            }
        });
        timer.start();
        dbConnector connect = new dbConnector();
        Session sess = Session.getInstance();
        displayname.setText(""+ sess.getFname()+ " "+ sess.getLname());
        fullnamedisp.setText(""+ sess.getFname()+ " "+ sess.getLname());
        fnamedisp.setText("First Name: "+ sess.getFname());
        lnamedisp.setText("Last Name: "+ sess.getLname());
        contactdisp.setText("Contact Number: "+ sess.getNum());
        statusdisp.setText("Status: "+ sess.getStatus());
        usernamedisp.setText("Username: "+ sess.getUsername());
        passdisp.setText("Password: "+sess.getPassword());
    }//GEN-LAST:event_formWindowActivated

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        doctorAppointments open = new doctorAppointments();
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        doctorPatients open = new doctorPatients();
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        jPanel11.setBackground(new Color(60, 91, 111));
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
        jPanel11.setBackground(new Color(21, 52, 72));
    }//GEN-LAST:event_jPanel11MouseExited

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        jPanel10.setBackground(new Color(60, 91, 111));
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        jPanel10.setBackground(new Color(21, 52, 72));
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(new Color(60, 91, 111));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(new Color(21, 52, 72));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        jPanel7.setBackground(new Color(60, 91, 111));
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        jPanel7.setBackground(new Color(21, 52, 72));
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        doctorDash open = new doctorDash();
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctorProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Doctor;
    private javax.swing.JLabel Doctor1;
    private javax.swing.JLabel contactdisp;
    private javax.swing.JLabel date_disp;
    private javax.swing.JLabel displayname;
    private javax.swing.JLabel fnamedisp;
    private javax.swing.JLabel fnamedisp6;
    private javax.swing.JLabel fnamedisp7;
    private javax.swing.JLabel fnamedisp8;
    private javax.swing.JLabel fnamedisp9;
    private javax.swing.JLabel fullnamedisp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lnamedisp;
    private javax.swing.JLabel passdisp;
    private javax.swing.JLabel statusdisp;
    private javax.swing.JLabel time_disp;
    private javax.swing.JLabel usernamedisp;
    // End of variables declaration//GEN-END:variables
}
